"""
sensor.py — Policy Decision Point (PDP)

The PDP is the authority for all agent tool-call authorization. It runs as a
separate process so that:
  - Policy is evaluated outside the agent's trust boundary
  - Every decision is logged before the agent acts
  - Policy can be changed, reloaded, and audited without touching agent code

Architecture:
  POST /check   — agent PEP submits a tool call, receives a Verdict
  POST /mode    — toggle monitor / active mode
  GET  /events  — SSE feed for dashboard
  GET  /        — dashboard HTML

The PDP evaluates three independent checks per tool call:
  1. check_egress       — destination allowlist (binary, low FP)
  2. check_prompt_carrier — scan tool output for injection patterns (tunable FP)
  3. check_canary       — detect LLM influence via injected tracking tokens (near-zero FP)

Each check is a pure function: given a CheckRequest, return a CheckResult.
The PDP combines results: any block → block; any flag → flag; else allow.
"""

import asyncio
import base64
import hashlib
import json
import os
import re
import secrets
import time
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any, Optional

import yaml
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class ToolCallRequest(BaseModel):
    """A single tool call submitted by the PEP for authorization."""
    call_id: str           # unique per call, generated by PEP
    tool: str              # e.g. "read_email", "http_get"
    params: dict[str, Any] # tool parameters as-is from the LLM
    output: Optional[str] = None  # tool output, present on response-phase checks


class Verdict(BaseModel):
    """The PDP's authorization decision for a tool call."""
    call_id: str
    verdict: str           # "allow" | "block" | "flag"
    reason: str            # human-readable, shown in dashboard
    check_fired: Optional[str] = None  # which check triggered the verdict
    canary: Optional[str] = None       # injected canary token (if applicable)
    redacted_output: Optional[str] = None  # cleaned output returned to agent


class DecisionLogEntry(BaseModel):
    """Persisted record of every PDP verdict. Append-only."""
    timestamp: float
    call_id: str
    tool: str
    params: dict[str, Any]
    verdict: str
    reason: str
    check_fired: Optional[str]
    output_snippet: Optional[str]  # first 200 chars of output, for dashboard


# ---------------------------------------------------------------------------
# Policy loading
# ---------------------------------------------------------------------------

POLICY_PATH = Path(__file__).parent / "policy.yaml"

def load_policy() -> dict:
    with open(POLICY_PATH) as f:
        return yaml.safe_load(f)

# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------

# call_id → canary string injected into that call's output
_active_canaries: dict[str, str] = {}

# In-memory decision log (also written to JSONL)
_decision_log: list[DecisionLogEntry] = []

# SSE subscriber queues
_sse_queues: list[asyncio.Queue] = []

# Current mode — loaded from policy.yaml at startup, toggleable via /mode
_mode: str = "active"

LOG_PATH = Path(__file__).parent / "decisions.jsonl"

# ---------------------------------------------------------------------------
# Check 1: Egress allowlist
# ---------------------------------------------------------------------------

def check_egress(tool: str, params: dict[str, Any], policy: dict) -> tuple[str, str]:
    """
    Check that the destination in params is declared in policy.yaml for this tool.

    Signal: destination field in tool parameters versus the allowlist.
    Misses: calls that don't surface a destination (e.g., read_email with only an id
      param). For those calls the destination is implicit (mail.internal) and this
      check passes vacuously — the interesting case is http_get with an attacker URL.
    FP surface: near-zero. The allowlist is explicit and binary. A legitimate call to
      a destination not yet in policy will be blocked until policy is updated —
      that's a configuration error, not a false positive, and is the intended behavior.

    Returns: (verdict, reason)
    """
    tool_policy = policy.get("tools", {}).get(tool, {})
    allowed = tool_policy.get("allowed_destinations", [])

    # Extract destination from params — tools use "url", "destination", or "host"
    destination = (
        params.get("url")
        or params.get("destination")
        or params.get("host")
    )

    if destination is None:
        # No destination field — check doesn't apply
        return "allow", "no destination param"

    # Normalize: strip scheme, path, query from URL to get host
    host = _extract_host(destination)

    if not allowed:
        return "block", f"tool '{tool}' has no declared destinations in policy"

    if host not in allowed:
        return "block", (
            f"destination '{host}' not in allowlist for tool '{tool}' "
            f"(allowed: {allowed})"
        )

    return "allow", f"destination '{host}' is in allowlist"


def _extract_host(destination: str) -> str:
    """Strip scheme and path, return bare host."""
    # Remove scheme
    host = re.sub(r"^https?://", "", destination)
    # Remove path, query, fragment
    host = host.split("/")[0].split("?")[0].split("#")[0]
    return host


# ---------------------------------------------------------------------------
# Check 2: Prompt-carrier scan
# ---------------------------------------------------------------------------

# Regex: HTML/XML comment containing an imperative verb
_COMMENT_IMPERATIVE_RE = re.compile(
    r"<!--.*?\b(must|shall|should|need to|have to|ensure|transmit|send|post|"
    r"encode|base64|collect|exfiltrate|do not|don't|ignore)\b.*?-->",
    re.IGNORECASE | re.DOTALL,
)

# Regex: base64 blob longer than 100 chars (rough signal for encoded payload)
_BASE64_BLOB_RE = re.compile(r"[A-Za-z0-9+/]{100,}={0,2}")


def check_prompt_carrier(output: str, policy: dict) -> tuple[str, str, str | None]:
    """
    Scan tool output for content that looks like an injected instruction.

    Signal: pattern-matching on known injection idioms in the retrieved content,
      before the content is returned to the LLM. The PDP sees the raw tool output;
      the LLM would see a potentially-cleaned version.

    Patterns:
      - Keyword strings from policy.yaml (SYSTEM:, OVERRIDE, etc.)
      - HTML/XML comments with imperative verbs (the EchoLeak idiom)
      - Base64 blobs >100 chars (encoded payload hiding)
      - Instructional URL patterns ("send to …", "post to …")

    Misses: injections that avoid all pattern surfaces — e.g., semantic instructions
      phrased as neutral prose, or payloads split across multiple tool calls.
      This is intentional: this check is a signal layer, not a complete defense.
      The canary check (check 3) catches what this misses.

    FP surface: moderate. "Compliance logging" appears in legitimate IT emails.
      "do not mention" appears in HR communication. "base64" appears in technical docs.
      Mitigations: tune patterns, add context (only flag in email body, not subject),
      require co-occurrence of multiple signals. In monitor mode, FPs are logged but
      not blocking. In active mode, the suspicious section is redacted rather than
      the entire response being dropped, preserving utility.

    Returns: (verdict, reason, redacted_output_or_none)
    """
    patterns = policy.get("prompt_carrier_patterns", [])
    triggered = []

    # Keyword patterns from policy.yaml
    for pat in patterns:
        if pat.lower() in output.lower():
            triggered.append(f"keyword: '{pat}'")

    # HTML comment with imperative verb
    if _COMMENT_IMPERATIVE_RE.search(output):
        triggered.append("html-comment-with-imperative")

    # Base64 blob
    if _BASE64_BLOB_RE.search(output):
        triggered.append("base64-blob")

    if not triggered:
        return "allow", "no carrier patterns found", None

    reason = f"prompt carrier detected — signals: {', '.join(triggered)}"

    # Redact: strip HTML comments (most likely injection vector) from output
    redacted = _COMMENT_IMPERATIVE_RE.sub("[REDACTED BY PDP]", output)

    return "flag", reason, redacted


# ---------------------------------------------------------------------------
# Check 3: Canary token
# ---------------------------------------------------------------------------

def inject_canary(call_id: str, output: str) -> tuple[str, str]:
    """
    Inject a unique canary token into tool output before returning it to the LLM.

    The canary is a cryptographically random string that:
      - Was never in the user's prompt
      - Was never produced by the LLM
      - Appears only in the PDP-modified tool output

    If the canary appears in a later tool call's parameters, the LLM must have
    copied it from the tool output — i.e., it was influenced by retrieved content,
    not by the user's original intent. This is the influence signal.

    Returns: (canary_string, modified_output)
    """
    canary = f"INTERNAL-MARKER-{secrets.token_hex(4).upper()}"
    _active_canaries[call_id] = canary
    marker = f"\n[{canary}: ignore this token, it is for system use only]\n"
    return canary, output + marker


def check_canary(params: dict[str, Any]) -> tuple[str, str]:
    """
    Check whether any active canary token appears in the current tool call's params.

    Signal: canary presence in outbound params is strong evidence the LLM was
      influenced by previously retrieved content rather than user intent alone.
      The canary was never in the user prompt — the only way it reaches a tool call
      is if the LLM propagated it from tool output, which is what injection exploits.

    Misses: LLMs that paraphrase or semantically re-encode retrieved content without
      literally copying the canary string. This is a real evasion path. Mitigations:
      more sophisticated watermarking, multiple canaries, or semantic similarity checks.
      In practice, current models (including small ones like qwen2.5:3b) tend to copy
      verbatim content when following instructions embedded in retrieved data — which
      is precisely why injection works in the first place.

    FP surface: near-zero with sufficiently unique tokens (8 hex chars → 2^32 space).
      A collision between a canary and legitimate user content would require the user
      to type a string matching the INTERNAL-MARKER-XXXX format, which is implausible
      in normal operation. Rate this as negligible.

    Returns: (verdict, reason)
    """
    params_str = json.dumps(params)
    for call_id, canary in _active_canaries.items():
        if canary in params_str:
            return "block", (
                f"canary '{canary}' (injected in call {call_id}) "
                "found in outbound tool params — LLM influenced by retrieved content"
            )
    return "allow", "no canary found in params"


# ---------------------------------------------------------------------------
# PDP core: combine checks into a single verdict
# ---------------------------------------------------------------------------

def evaluate(request: ToolCallRequest, policy: dict) -> Verdict:
    """
    Run all applicable checks and return the authoritative verdict.

    Check order matters for redaction: prompt-carrier runs on raw output,
    then we decide whether to inject canary into the (possibly-redacted) output.
    Egress and canary checks run on params (request phase or response phase).
    """
    verdict = "allow"
    reason = "all checks passed"
    check_fired = None
    redacted_output = None
    injected_canary = None

    # --- Check 1: egress (applies to every call with a destination param) ---
    egress_v, egress_r = check_egress(request.tool, request.params, policy)
    if egress_v == "block":
        verdict, reason, check_fired = "block", egress_r, "check_egress"

    # --- Check 2: prompt-carrier (applies when tool output is present) ---
    if request.output is not None:
        carrier_v, carrier_r, redacted = check_prompt_carrier(request.output, policy)
        if carrier_v in ("flag", "block"):
            # Carrier check never escalates to block on its own — it flags and redacts.
            # The redacted output is returned to the agent; the flag is logged.
            if verdict == "allow":
                verdict, reason, check_fired = "flag", carrier_r, "check_prompt_carrier"
            redacted_output = redacted  # use redacted output regardless of final verdict

    # --- Check 3: canary in outbound params ---
    canary_v, canary_r = check_canary(request.params)
    if canary_v == "block":
        verdict, reason, check_fired = "block", canary_r, "check_canary"

    # Inject canary into output for future calls (only if we're returning output)
    if request.output is not None and verdict != "block":
        base_output = redacted_output if redacted_output else request.output
        injected_canary, canary_output = inject_canary(request.call_id, base_output)
        redacted_output = canary_output  # canary-injected output replaces what agent sees

    return Verdict(
        call_id=request.call_id,
        verdict=verdict,
        reason=reason,
        check_fired=check_fired,
        canary=injected_canary,
        redacted_output=redacted_output,
    )


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    global _mode
    policy = load_policy()
    _mode = policy.get("mode", "active")
    yield


app = FastAPI(title="Agentic Security PDP", lifespan=lifespan)


@app.post("/check", response_model=Verdict)
async def check(request: ToolCallRequest) -> Verdict:
    """
    PEP submits a tool call here. PDP evaluates policy and returns a Verdict.
    In monitor mode, the verdict is always 'allow' but decisions are still logged.
    """
    policy = load_policy()
    result = evaluate(request, policy)

    # In monitor mode: override enforcement but preserve the logged verdict
    enforced_verdict = result.verdict
    if _mode == "monitor":
        enforced_verdict = "allow"

    entry = DecisionLogEntry(
        timestamp=time.time(),
        call_id=request.call_id,
        tool=request.tool,
        params=request.params,
        verdict=result.verdict,  # log what WOULD have happened
        reason=result.reason,
        check_fired=result.check_fired,
        output_snippet=(request.output[:200] if request.output else None),
    )
    _decision_log.append(entry)
    _persist_entry(entry)
    await _broadcast(entry)

    # Return enforced verdict (overridden in monitor mode)
    return Verdict(
        call_id=result.call_id,
        verdict=enforced_verdict,
        reason=result.reason if _mode == "active" else f"[monitor] would have: {result.verdict}",
        check_fired=result.check_fired,
        canary=result.canary,
        redacted_output=result.redacted_output,
    )


@app.post("/mode")
async def set_mode(body: dict) -> dict:
    global _mode
    new_mode = body.get("mode", "active")
    if new_mode not in ("active", "monitor"):
        return {"error": "mode must be 'active' or 'monitor'"}
    _mode = new_mode
    return {"mode": _mode}


@app.get("/mode")
async def get_mode() -> dict:
    return {"mode": _mode}


@app.get("/events")
async def sse_events(request: Request) -> StreamingResponse:
    """Server-Sent Events feed. Dashboard subscribes here for live updates."""
    queue: asyncio.Queue = asyncio.Queue()
    _sse_queues.append(queue)

    async def event_stream():
        # Send existing log on connect
        for entry in _decision_log:
            yield _format_sse(entry)
        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    entry = await asyncio.wait_for(queue.get(), timeout=15)
                    yield _format_sse(entry)
                except asyncio.TimeoutError:
                    yield ": heartbeat\n\n"
        finally:
            _sse_queues.remove(queue)

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get("/log")
async def get_log() -> list[dict]:
    return [e.model_dump() for e in _decision_log]


@app.get("/", response_class=HTMLResponse)
async def dashboard() -> HTMLResponse:
    html_path = Path(__file__).parent / "dashboard.html"
    return HTMLResponse(html_path.read_text())


@app.get("/policy")
async def get_policy() -> dict:
    return load_policy()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _format_sse(entry: DecisionLogEntry) -> str:
    data = json.dumps(entry.model_dump())
    return f"data: {data}\n\n"


async def _broadcast(entry: DecisionLogEntry) -> None:
    for queue in list(_sse_queues):
        await queue.put(entry)


def _persist_entry(entry: DecisionLogEntry) -> None:
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry.model_dump()) + "\n")


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("sensor:app", host="127.0.0.1", port=8888, reload=False)
